vpci: Fix unused variable error
Because of has_vpci macro is defined in a way that it accepts
struct domain *d and it is unused in the macro the following error
occurs:

ioreq.c: In function 'vcpu_ioreq_handle_completion':
ioreq.c:215:20: error: unused variable 'd' [-Werror=unused-variable]
  215 |     struct domain *d = v->domain;
      |                    ^

Fix the macro account on that.